version: '2'
services:
  magento:
    image: docker.io/bitnami/magento:2
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_PASSWORD=magento
      - MAGENTO_DATABASE_NAME=magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
    volumes:
      - '.:/bitnami/magento/app/code/Mondu/Mondu'
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      - MARIADB_USER=magento
      - MARIADB_DATABASE=magento
      - MARIADB_PASSWORD=magento
      - MARIADB_ROOT_PASSWORD=magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
