version: "3"
services:
  magento:
    container_name: magento
    build: .
    platform: linux/amd64
    ports:
      - 80:8080
    environment:
      - BITNAMI_DEBUG=true
      - MAGENTO_HOST=localhost
      - MAGENTO_MODE=developer
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_ELASTICSEARCH_HOST=elasticsearch
      - MAGENTO_ELASTICSEARCH_PORT_NUMBER=9200
      - MAGENTO_USERNAME=mondu
      - MAGENTO_PASSWORD=mondu123
      - MAGENTO_EMAIL=mondu@mondu.ai
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_MEMORY_LIMIT=5120M
    volumes:
      - magento_data:/bitnami/magento
      - .:/bitnami/magento/vendor/mondu/magento2-payment/
      - ./auth.json:/bitnami/magento/auth.json
    depends_on:
      mariadb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    working_dir: /bitnami/magento
    mem_limit: 5120MB
    memswap_limit: 5120MB
    mem_swappiness: 0
  mariadb:
    image: bitnami/mariadb:10.4
    platform: linux/amd64
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - mariadb_data:/bitnami/mariadb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root ping --silent"]
      interval: 30s
      timeout: 30s
      retries: 3
  elasticsearch:
    image: bitnami/elasticsearch:7
    platform: linux/amd64
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 50
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
