<?php
/** @var \Mondu\Mondu\Block\Memo $block */
    $invoices = $block->invoices();
    $mapping = $block->getInvoiceMappings();
?>

<?php if ($block->render()): ?>
<div class="field choice admin__field">
    <?= $block->escapeHtml($block->getPaymentMethod()) ?>
    <div class="admin__field">
        <label for="history_status" class="admin__field-label">Invoice to memo</label>
        <div class="admin__field-control">
            <select name="creditmemo[creditmemo_mondu_id]" id="history_status" class="admin__control-select">
                <?php $i = 0; foreach ($mapping as $key => $item): ?>
                    <option value="<?= $block->escapeHtml($item['uuid']) ?>"
                        <?php
                            (isset($item['state']) && $item['state'] === 'complete') ?
                            $block->escapeHtml('disabled') :
                            ''
                        ?>
                    >
                        INVOICE: <?= $block->escapeHtml($key) ?> State: <?= $block->escapeHtml($item['state']) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>
<?php endif; ?>
