name: PHP CodeSniffer

on:
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer

    - name: Install dependencies
      run: composer install

    - name: Install Magento 2 Code Sniffer and PHP Mess Detector
      run: |
        composer require magento/magento-coding-standard
        composer require phpmd/phpmd

    - name: Run PHP Mess Detector
      run: vendor/bin/phpmd . text cleancode,codesize,controversial,design,naming,unusedcode

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs --standard=PSR12,Magento2 .

